---
title: "DV Chapter 04 Practice"
author: "Ava Foster"
format: html
embed-resources: true
editor: visual
---

```{r}
library(tidyverse)
```

```{r}
library(gapminder)

gapminder <- gapminder 
```

```{r}
p <- ggplot(data = gapminder,
            mapping = aes(x = year,
                          y = gdpPercap))
p + geom_line() 
```

```{r}
p <- ggplot(data = gapminder,
            mapping = aes(x = year,
                          y = gdpPercap))
p + geom_line(aes(group=country)) 
```

```{r}
p <- ggplot(data = gapminder,
            mapping = aes(x = year,
                          y = gdpPercap))
p + geom_line(aes(group=country)) + facet_wrap(~ continent)
```

```{r}
p <- ggplot(data = gapminder,
            mapping = aes(x = year,
                          y = gdpPercap))
p + geom_line(color="gray70", aes(group=country)) + 
  geom_smooth(size = 1.1, method = "loess", se = FALSE) +
  scale_y_log10(labels=scales::dollar) +
  facet_wrap(~ continent, ncol = 5) +
  labs(x = "Year", y = "GDP Per Capita", title = "GDP Per Capita on Five Continents")
```
